server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  level:
    root: DEBUG

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: coderef
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write

spring:
    datasource:  
        initialize: true
        data: classpath:/sql/data-oauth.sql      
        driver-class-name: org.mariadb.jdbc.Driver       
        password: 
        hikari:
            minimum-idle: 1
            maximum-pool-size: 10
        platform: mysql
        schema: classpath:/sql/schema-oauth.sql        
        url: jdbc:mariadb://localhost:3306/oauth?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: update
        hibernate:
            ddl-auto: create
        show-sql: true