server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
    lease:
      duration: 5
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  level:
    root: DEBUG

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: coderef
            client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
            resource-ids: resources
            scope: read,write

spring:
    datasource:  
        data: classpath:/sql/data-oauth.sql      
        driver-class-name: com.mysql.cj.jdbc.Driver        
        password: 
        platform: mysql
        schema: classpath:/sql/schema-oauth.sql        
        url: jdbc:mysql://localhost:3306/oauth?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL57Dialect
        generate-ddl: true
        show-sql: true
